// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQESq6AoviXWMdNfdEaoVVRmOP6_75BtY',
    appId: '1:295172946895:web:69c3a1b7e205b5a65e30ba',
    messagingSenderId: '295172946895',
    projectId: 't-talk-3a00a',
    authDomain: 't-talk-3a00a.firebaseapp.com',
    storageBucket: 't-talk-3a00a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgPjRnjnJHcl8SKH4Kjc-pazCTJOIRkQo',
    appId: '1:295172946895:android:0adbd86256f088835e30ba',
    messagingSenderId: '295172946895',
    projectId: 't-talk-3a00a',
    storageBucket: 't-talk-3a00a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6HJT4PmLpugb5nhxl50BNdXolJi63HwU',
    appId: '1:295172946895:ios:2e4300b2218caa045e30ba',
    messagingSenderId: '295172946895',
    projectId: 't-talk-3a00a',
    storageBucket: 't-talk-3a00a.firebasestorage.app',
    iosBundleId: 'com.example.ttalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6HJT4PmLpugb5nhxl50BNdXolJi63HwU',
    appId: '1:295172946895:ios:2e4300b2218caa045e30ba',
    messagingSenderId: '295172946895',
    projectId: 't-talk-3a00a',
    storageBucket: 't-talk-3a00a.firebasestorage.app',
    iosBundleId: 'com.example.ttalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQESq6AoviXWMdNfdEaoVVRmOP6_75BtY',
    appId: '1:295172946895:web:6fae64b0c05f0a135e30ba',
    messagingSenderId: '295172946895',
    projectId: 't-talk-3a00a',
    authDomain: 't-talk-3a00a.firebaseapp.com',
    storageBucket: 't-talk-3a00a.firebasestorage.app',
  );
}
